services:
  
  tarefasfrontend:
    image: LuizGuilhes18/tarefafrontend:latest
    container_name: frontend
    depends_on:
      tarefasbackend:
        condition: service_started
    ports:
      - 4200:4200  
    networks:
      - dev-network

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tarefa
    ports:
      - 5432:5432
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 10s
      retries: 5    

  tarefasbackend:
    image: LuizGuilhes18/tarefabackend:latest
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tarefa
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root    
    depends_on:
      db:
       condition: service_healthy     
    networks:
      - dev-network
  
networks:
  dev-network:
    driver: bridge
