services:
  
  tarefasfrontend:
    image: augustomello09/tarefafrontend:latest
    container_name: frontend
    depends_on:
      tarefasbackend:
        condition: service_started
    ports:
      - 4200:4200  
    networks:
      - dev-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8000:80
    networks:
      - dev-network    
  
  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tarefa
    ports:
      - 3307:3306
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 5    

  tarefasbackend:
    image: augustomello09/tarefabackend:latest
    container_name: backend
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/tarefa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root    
    depends_on:
      db:
       condition: service_healthy     
    networks:
      - dev-network
  
              
networks:
  dev-network:
    driver: bridge